backend:
  command: "/root/.virtualenv/moni/bin/python /prestamos/manage.py runserver 0.0.0.0:8000"
  ports:
    - "8000:8000"
  volumes:
    - ..:/backend
  build: .
  links:
    - db
    - redis
    - mongo
    - rabbitmq
frontend:
    volumes:
    - ..:/frontend
nginx:
  image: nginx
celery:
  command: "/root/.virtualenv/moni/bin/python celery worker -E -Q celery,notifications --autoreload --loglevel=debug"
  volumes:
    - ..:/backend
  build: .
  environment:
    C_FORCE_ROOT: 'true'
  links:
    - db
    - redis
    - mongo
    - rabbitmq
db:
  image: postgre
redis:
  image: redis
  ports:
    - "6379:6379"
mongo:
  image: mongo
rabbitmq:
  image: rabbitmq
  ports:
    - "5672:5672"  # we forward this port because it's useful for debugging
    - "15672:15672"  # here, we can access rabbitmq management plugin
